version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2024.01
    steps:
      - checkout  
      - run:
          name: build
          command: gcc main.c

workflows:
  build:
    jobs:
      - build
